# Generated by Django 4.0 on 2022-02-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='information_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add file'),
        ),
    ]
