# Generated by Django 4.0 on 2022-02-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_information_information_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='information_image',
            new_name='information_file',
        ),
    ]
